FROM node:22-slim

RUN apt-get update && apt-get install -y --no-install-recommends \
    git \
    && rm -rf /var/lib/apt/lists/*

RUN npm install -g pnpm

RUN git clone https://github.com/imputnet/cobalt.git /cobalt

WORKDIR /cobalt/api

RUN pnpm install

ENV API_URL=http://localhost:9000/
ENV API_PORT=9000

EXPOSE 9000

CMD ["pnpm", "start"]
